"""phases

Revision ID: 6e3b2b3e56f0
Revises: 51ebcf9d0049
Create Date: 2022-02-14 15:03:53.139327

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6e3b2b3e56f0'
down_revision = '51ebcf9d0049'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    phase_code = op.create_table('phase_codes',
                                 sa.Column('sort_order', sa.Integer(), nullable=True),
                                 sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                                 sa.Column('work_type_id', sa.Integer(), nullable=False),
                                 sa.Column('start_event', sa.String(), nullable=True),
                                 sa.Column('end_event', sa.String(), nullable=True),
                                 sa.Column('duration', sa.Integer(), nullable=True),
                                 sa.Column('legislated', sa.Boolean(), nullable=True),
                                 sa.Column('name', sa.String(), nullable=True),
                                 sa.ForeignKeyConstraint(['work_type_id'], ['work_types.id'], ),
                                 sa.PrimaryKeyConstraint('id')
                                 )
    op.bulk_insert(
        phase_code,
        [
            {
                'sort_order': 1,
                'name': 'Early Engagement',
                'work_type_id': 6,
                'start_event': 'Initial Project Description accepted',
                'end_event': 'Summary of Engagement Issued',
                'duration': 90,
                'legislated': True
            },
            {
                'sort_order': 2,
                'name': 'Proponent Time: Project Description',
                'work_type_id': 6,
                'start_event': 'Day after the posting of Summary of Engagment',
                'end_event': 'Day before the submission of DPD',
                'duration': 365,
                'legislated': False
            },
            {
                'sort_order': 3,
                'name': 'Readiness Decision',
                'work_type_id': 6,
                'start_event': 'Submission of DPD',
                'end_event': 'Ministers\' Decision',
                'duration': 60,
                'legislated': False
            }, {
            'sort_order': 4,
            'name': 'Process Planning',
            'work_type_id': 6,
            'start_event': 'Day after Ministers\' Decision',
            'end_event': 'Process Order Issued',
            'duration': 120,
            'legislated': True
        }, {
            'sort_order': 5,
            'name': 'Proponent Time: Application Development',
            'work_type_id': 6,
            'start_event': 'Day after Process Order issued',
            'end_event': 'Day before the acceptance of the Application',
            'duration': 1095,
            'legislated': False
        }, {
            'sort_order': 6,
            'name': 'Application Development & Review',
            'work_type_id': 6,
            'start_event': 'Application for an EAC accepted',
            'end_event': 'Notice Regarding Application',
            'duration': 180,
            'legislated': True
        }, {
            'sort_order': 7,
            'name': 'Proponent Time: Revised Application',
            'work_type_id': 6,
            'start_event': 'Day after Notice',
            'end_event': 'Day before Revised Application',
            'duration': 365,
            'legislated': False
        }, {
            'sort_order': 8,
            'name': 'Effects Assessment',
            'work_type_id': 6,
            'start_event': 'Revised Application Submitted',
            'end_event': 'Draft Assessment Report is issued',
            'duration': 110,
            'legislated': True
        }, {
            'sort_order': 9,
            'name': 'Recommendation',
            'work_type_id': 6,
            'start_event': 'PECP starts for Draft Assessment Report?',
            'end_event': 'Package sent to Ministers',
            'duration': 40,
            'legislated': True
        }, {
            'sort_order': 10,
            'name': 'Referral/Decision',
            'work_type_id': 6,
            'start_event': 'Referral Package Received',
            'end_event': 'Minister\'s Decision',
            'duration': 30,
            'legislated': True
        }
        ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phase_codes')
    # ### end Alembic commands ###
